<?php

declare(strict_types=1);

namespace ChuckBartowski\ScalewaySdk\Model\AuditTrail;

final readonly class Resource
{
    public function __construct(
        public ?string $id = null,
        public mixed $type = null,
        public ?string $createdAt = null,
        public ?string $updatedAt = null,
        public ?string $deletedAt = null,
        public ?string $name = null,
        public ?array $secmSecretInfo = null,
        public ?array $secmSecretVersionInfo = null,
        public ?array $kubeClusterInfo = null,
        public ?array $kubePoolInfo = null,
        public ?array $kubeNodeInfo = null,
        public ?array $kubeAclInfo = null,
        public ?array $keymKeyInfo = null,
        public ?array $secretManagerSecretInfo = null,
        public ?array $secretManagerVersionInfo = null,
        public ?array $keyManagerKeyInfo = null,
        public ?array $accountUserInfo = null,
        public ?array $accountOrganizationInfo = null,
        public ?array $instanceServerInfo = null,
        public ?array $appleSiliconServerInfo = null,
        public ?array $accountProjectInfo = null,
        public ?array $baremetalServerInfo = null,
        public ?array $baremetalSettingInfo = null,
        public ?array $ipamIpInfo = null,
        public ?array $loadBalancerLbInfo = null,
        public ?array $loadBalancerIpInfo = null,
        public ?array $loadBalancerFrontendInfo = null,
        public ?array $loadBalancerBackendInfo = null,
        public ?array $loadBalancerRouteInfo = null,
        public ?array $loadBalancerAclInfo = null,
        public ?array $loadBalancerCertificateInfo = null,
        public ?array $edgeServicesPlanInfo = null,
        public ?array $edgeServicesPipelineInfo = null,
        public ?array $edgeServicesDnsStageInfo = null,
        public ?array $edgeServicesTlsStageInfo = null,
        public ?array $edgeServicesCacheStageInfo = null,
        public ?array $edgeServicesRouteStageInfo = null,
        public ?array $edgeServicesRouteRulesInfo = null,
        public ?array $edgeServicesWafStageInfo = null,
        public ?array $edgeServicesBackendStageInfo = null,
        public ?array $accountContractSignatureInfo = null,
        public ?array $vpcSubnetInfo = null,
        public ?array $vpcRouteInfo = null,
        public ?array $vpcPrivateNetworkInfo = null,
        public ?array $auditTrailExportJobInfo = null,
        public ?array $vpcGwGatewayInfo = null,
        public ?array $vpcGwGatewayNetworkInfo = null,
        public ?array $appleSiliconRunnerInfo = null,
        public ?array $auditTrailAlertRuleInfo = null,
        public ?array $vpcConnectorInfo = null,
        public ?array $instancePrivateNetworkInterfaceInfo = null,
        public ?array $vpcIngressRuleInfo = null,
        public ?array $observabilityContactPointInfo = null,
        public ?array $observabilityAlertRuleInfo = null,
        public ?array $edgeServicesVpcEndpointInfo = null,
        public array $raw = [],
    ) {
    }

    public static function from(array $data): self
    {
        return new self(
            isset($data['id']) && \is_scalar($data['id']) ? (string) $data['id'] : null,
            $data['type'] ?? null,
            isset($data['created_at']) && \is_scalar($data['created_at']) ? (string) $data['created_at'] : null,
            isset($data['updated_at']) && \is_scalar($data['updated_at']) ? (string) $data['updated_at'] : null,
            isset($data['deleted_at']) && \is_scalar($data['deleted_at']) ? (string) $data['deleted_at'] : null,
            isset($data['name']) && \is_scalar($data['name']) ? (string) $data['name'] : null,
            \is_array($data['secm_secret_info'] ?? null) ? $data['secm_secret_info'] : null,
            \is_array($data['secm_secret_version_info'] ?? null) ? $data['secm_secret_version_info'] : null,
            \is_array($data['kube_cluster_info'] ?? null) ? $data['kube_cluster_info'] : null,
            \is_array($data['kube_pool_info'] ?? null) ? $data['kube_pool_info'] : null,
            \is_array($data['kube_node_info'] ?? null) ? $data['kube_node_info'] : null,
            \is_array($data['kube_acl_info'] ?? null) ? $data['kube_acl_info'] : null,
            \is_array($data['keym_key_info'] ?? null) ? $data['keym_key_info'] : null,
            \is_array($data['secret_manager_secret_info'] ?? null) ? $data['secret_manager_secret_info'] : null,
            \is_array($data['secret_manager_version_info'] ?? null) ? $data['secret_manager_version_info'] : null,
            \is_array($data['key_manager_key_info'] ?? null) ? $data['key_manager_key_info'] : null,
            \is_array($data['account_user_info'] ?? null) ? $data['account_user_info'] : null,
            \is_array($data['account_organization_info'] ?? null) ? $data['account_organization_info'] : null,
            \is_array($data['instance_server_info'] ?? null) ? $data['instance_server_info'] : null,
            \is_array($data['apple_silicon_server_info'] ?? null) ? $data['apple_silicon_server_info'] : null,
            \is_array($data['account_project_info'] ?? null) ? $data['account_project_info'] : null,
            \is_array($data['baremetal_server_info'] ?? null) ? $data['baremetal_server_info'] : null,
            \is_array($data['baremetal_setting_info'] ?? null) ? $data['baremetal_setting_info'] : null,
            \is_array($data['ipam_ip_info'] ?? null) ? $data['ipam_ip_info'] : null,
            \is_array($data['load_balancer_lb_info'] ?? null) ? $data['load_balancer_lb_info'] : null,
            \is_array($data['load_balancer_ip_info'] ?? null) ? $data['load_balancer_ip_info'] : null,
            \is_array($data['load_balancer_frontend_info'] ?? null) ? $data['load_balancer_frontend_info'] : null,
            \is_array($data['load_balancer_backend_info'] ?? null) ? $data['load_balancer_backend_info'] : null,
            \is_array($data['load_balancer_route_info'] ?? null) ? $data['load_balancer_route_info'] : null,
            \is_array($data['load_balancer_acl_info'] ?? null) ? $data['load_balancer_acl_info'] : null,
            \is_array($data['load_balancer_certificate_info'] ?? null) ? $data['load_balancer_certificate_info'] : null,
            \is_array($data['edge_services_plan_info'] ?? null) ? $data['edge_services_plan_info'] : null,
            \is_array($data['edge_services_pipeline_info'] ?? null) ? $data['edge_services_pipeline_info'] : null,
            \is_array($data['edge_services_dns_stage_info'] ?? null) ? $data['edge_services_dns_stage_info'] : null,
            \is_array($data['edge_services_tls_stage_info'] ?? null) ? $data['edge_services_tls_stage_info'] : null,
            \is_array($data['edge_services_cache_stage_info'] ?? null) ? $data['edge_services_cache_stage_info'] : null,
            \is_array($data['edge_services_route_stage_info'] ?? null) ? $data['edge_services_route_stage_info'] : null,
            \is_array($data['edge_services_route_rules_info'] ?? null) ? $data['edge_services_route_rules_info'] : null,
            \is_array($data['edge_services_waf_stage_info'] ?? null) ? $data['edge_services_waf_stage_info'] : null,
            \is_array($data['edge_services_backend_stage_info'] ?? null) ? $data['edge_services_backend_stage_info'] : null,
            \is_array($data['account_contract_signature_info'] ?? null) ? $data['account_contract_signature_info'] : null,
            \is_array($data['vpc_subnet_info'] ?? null) ? $data['vpc_subnet_info'] : null,
            \is_array($data['vpc_route_info'] ?? null) ? $data['vpc_route_info'] : null,
            \is_array($data['vpc_private_network_info'] ?? null) ? $data['vpc_private_network_info'] : null,
            \is_array($data['audit_trail_export_job_info'] ?? null) ? $data['audit_trail_export_job_info'] : null,
            \is_array($data['vpc_gw_gateway_info'] ?? null) ? $data['vpc_gw_gateway_info'] : null,
            \is_array($data['vpc_gw_gateway_network_info'] ?? null) ? $data['vpc_gw_gateway_network_info'] : null,
            \is_array($data['apple_silicon_runner_info'] ?? null) ? $data['apple_silicon_runner_info'] : null,
            \is_array($data['audit_trail_alert_rule_info'] ?? null) ? $data['audit_trail_alert_rule_info'] : null,
            \is_array($data['vpc_connector_info'] ?? null) ? $data['vpc_connector_info'] : null,
            \is_array($data['instance_private_network_interface_info'] ?? null) ? $data['instance_private_network_interface_info'] : null,
            \is_array($data['vpc_ingress_rule_info'] ?? null) ? $data['vpc_ingress_rule_info'] : null,
            \is_array($data['observability_contact_point_info'] ?? null) ? $data['observability_contact_point_info'] : null,
            \is_array($data['observability_alert_rule_info'] ?? null) ? $data['observability_alert_rule_info'] : null,
            \is_array($data['edge_services_vpc_endpoint_info'] ?? null) ? $data['edge_services_vpc_endpoint_info'] : null,
            $data,
        );
    }
}
